'use client';

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-gray-50 py-8">
      {/* Main Content */}
      <div className="container mx-auto px-4">
        <div className="max-w-4xl mx-auto bg-white rounded-xl shadow-lg flex flex-col hover:shadow-xl transition-shadow duration-300 max-h-[calc(100vh-4rem)]">
          {/* Header Section - Fixed */}
          <div className="bg-gradient-to-r from-[#2076C7] to-[#1CADA3] text-white py-8 px-6 text-center flex-shrink-0">
            <h1 className="text-3xl md:text-4xl font-bold mb-2">Privacy Policy</h1>
            <p className="text-blue-100 italic">Last Updated: January 1, 2024</p>
          </div>

          {/* Scrollable Content Section */}
          <div className="flex-1 overflow-y-auto">
            <div className="p-6 md:p-8 space-y-8">
              {/* Introduction */}
              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-[#2076C7] border-l-4 border-[#1CADA3] pl-4">1. Introduction</h2>
                <p className="text-gray-700 leading-relaxed">
                  This Privacy Policy (hereinafter referred to as &quot;Policy&quot;) is an electronic record governed by the Information Technology Act, 2000 (&quot;IT Act&quot;) and its allied rules, regulations, and guidelines. This Policy is generated by a computer system and does not require physical or electronic authentication.
                </p>
              </section>

              {/* Definitions */}
              <section className="space-y-6">
                <h2 className="text-2xl font-semibold text-[#2076C7] border-l-4 border-[#1CADA3] pl-4">2. Definitions</h2>
                
                <div className="grid gap-4">
                  {[
                    {
                      term: "User/Client",
                      definition: "refers to the individual accessing or using the Website and/or Mobile Application."
                    },
                    {
                      term: "Company",
                      definition: "refers to Infinity Arthvishva Advisory Private Limited and its affiliates or subsidiaries."
                    },
                    {
                      term: "Site/Website",
                      definition: "refers to www.infinityarthvishva.com and any other website owned or operated by the Company."
                    },
                    {
                      term: "Personal Information",
                      definition: "refers to any personal data provided by the User in accordance with the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data) Rules, 2011."
                    }
                  ].map((item, index) => (
                    <div 
                      key={index}
                      className="bg-gray-50 p-6 rounded-lg border-l-4 border-[#2076C7] hover:bg-gray-100 transition-colors duration-200"
                    >
                      <div className="font-semibold text-[#2076C7] mb-2">{item.term}</div>
                      <p className="text-gray-700">{item.definition}</p>
                    </div>
                  ))}
                </div>
              </section>

              {/* Collection of Information */}
              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-[#2076C7] border-l-4 border-[#1CADA3] pl-4">3. Collection of Information</h2>
                <p className="text-gray-700">The Company collects personal and financial information from users, which may include:</p>
                <ul className="list-disc list-inside space-y-2 text-gray-700 ml-4">
                  <li>Name, contact details (email, phone number), postal address, demographic profile</li>
                  <li>Financial information, preferences regarding insurance or loan services</li>
                  <li>Other relevant data necessary for providing our services</li>
                </ul>
                <p className="text-gray-700 leading-relaxed">
                  Additionally, anonymous information may be collected, such as IP address, browser type, device details, and usage patterns, primarily for website optimization purposes.
                </p>
              </section>

              {/* Data Security Measures */}
              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-[#2076C7] border-l-4 border-[#1CADA3] pl-4">4. Data Security Measures</h2>
                <p className="text-gray-700 leading-relaxed">
                  The Company has implemented reasonable security practices and procedures to protect users&apos; personal data in compliance with the IT Act, 2000. However, the Company is not liable for any data loss that may occur beyond its reasonable control.
                </p>
              </section>

              {/* Privacy Protection Principles */}
              <section className="space-y-6">
                <h2 className="text-2xl font-semibold text-[#2076C7] border-l-4 border-[#1CADA3] pl-4">5. Privacy Protection Principles</h2>
                
                <div className="space-y-4">
                  <div>
                    <h3 className="text-xl font-semibold text-[#1CADA3] mb-3">Security</h3>
                    <p className="text-gray-700">The Company employs various security technologies to safeguard users&apos; personal information from unauthorized access, use, or disclosure.</p>
                  </div>
                  
                  <div>
                    <h3 className="text-xl font-semibold text-[#1CADA3] mb-3">Choice</h3>
                    <p className="text-gray-700">Users may choose whether to provide their personal information, although failure to do so may limit access to certain services.</p>
                  </div>
                  
                  <div>
                    <h3 className="text-xl font-semibold text-[#1CADA3] mb-3">Notice</h3>
                    <p className="text-gray-700">The Company collects personal information only for legitimate purposes and does not share it with third parties without user consent, unless required by law.</p>
                  </div>
                  
                  <div>
                    <h3 className="text-xl font-semibold text-[#1CADA3] mb-3">Access/Accuracy</h3>
                    <p className="text-gray-700">Users can update or correct their personal information upon request.</p>
                  </div>
                </div>
              </section>

              {/* Consent */}
              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-[#2076C7] border-l-4 border-[#1CADA3] pl-4">6. Consent</h2>
                <p className="text-gray-700 leading-relaxed">
                  By using the Website and Mobile Application, the User consents to the collection, use, and processing of their personal data as outlined in this Privacy Policy. Users also agree to receive communication related to services, products, and promotions from the Company and its partners.
                </p>
              </section>

              {/* Sharing of Personal Data */}
              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-[#2076C7] border-l-4 border-[#1CADA3] pl-4">7. Sharing of Personal Data</h2>
                <p className="text-gray-700 leading-relaxed">
                  The Company may share users&apos; personal data with partners, service providers, and regulatory authorities as necessary for service delivery, legal obligations, or to prevent fraud. All data sharing is done on a need-to-know basis, and users&apos; data will not be rented or sold.
                </p>
              </section>

              {/* Cookies */}
              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-[#2076C7] border-l-4 border-[#1CADA3] pl-4">8. Cookies</h2>
                <p className="text-gray-700 leading-relaxed">
                  The Company uses cookies to enhance user experience. Cookies help personalize services, but users have the option to disable them through their browser settings. If cookies are disabled, some features may be limited.
                </p>
              </section>

              {/* Changes to Privacy Policy */}
              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-[#2076C7] border-l-4 border-[#1CADA3] pl-4">9. Changes to Privacy Policy</h2>
                <p className="text-gray-700 leading-relaxed">
                  The Company reserves the right to modify this Privacy Policy at any time without prior notice. The revised Policy will be posted on this page, with the effective date indicated.
                </p>
              </section>

              {/* User Rights and Data Retention */}
              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-[#2076C7] border-l-4 border-[#1CADA3] pl-4">10. User Rights and Data Retention</h2>
                <p className="text-gray-700 leading-relaxed">
                  Users may request to delete their account or revoke consent for data processing by contacting the Company at <span className="bg-amber-50 px-2 py-1 rounded font-semibold text-amber-800">admin@infinityarthvishva.com</span>. The Company will retain user data as long as required for legal or operational purposes and in accordance with applicable laws.
                </p>
              </section>

              {/* Third-Party Links */}
              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-[#2076C7] border-l-4 border-[#1CADA3] pl-4">11. Third-Party Links</h2>
                <p className="text-gray-700 leading-relaxed">
                  The Company is not responsible for the privacy practices of third-party websites or services linked to or from the Website. Users are advised to review the privacy policies of third parties before providing personal information.
                </p>
              </section>

              {/* Contact Information */}
              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-[#2076C7] border-l-4 border-[#1CADA3] pl-4">12. Contact Information</h2>
                <p className="text-gray-700 leading-relaxed">
                  For any queries, concerns, or suggestions regarding this Privacy Policy, users may contact the Company at <span className="bg-amber-50 px-2 py-1 rounded font-semibold text-amber-800">admin@infinityarthvishva.com</span>.
                </p>
              </section>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}