'use client';

import { useState, useEffect } from 'react';

export default function TermsConditions() {
  const [activeSection, setActiveSection] = useState('');

  useEffect(() => {
    const handleScroll = () => {
      const sections = ['company-info', 'definitions', 'services', 'terms', 'acceptance'];
      const current = sections.find(section => {
        const element = document.getElementById(section);
        if (element) {
          const rect = element.getBoundingClientRect();
          return rect.top <= 100 && rect.bottom >= 100;
        }
        return false;
      });
      setActiveSection(current || '');
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const scrollToSection = (sectionId: string) => {
    const element = document.getElementById(sectionId);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="container mx-auto px-4">
        <div className="max-w-4xl mx-auto bg-white rounded-xl shadow-lg overflow-hidden hover:shadow-xl transition-shadow duration-300 flex flex-col max-h-[calc(100vh-4rem)]">
          {/* Header Section - Fixed */}
          <div className="bg-gradient-to-r from-[#2076C7] to-[#1CADA3] text-white py-8 px-6 text-center flex-shrink-0">
            <h1 className="text-3xl md:text-4xl font-bold mb-2">Terms of Use</h1>
            <p className="text-blue-100 italic">Effective Date: January 1, 2024</p>
          </div>

          {/* Scrollable Content Section */}
          <div className="flex-1 overflow-y-auto">
            <div className="p-6 md:p-8 space-y-8">
              {/* Important Notice Boxes */}
              <div className="space-y-4">
                <div className="bg-amber-50 p-6 rounded-lg border-l-4 border-amber-400">
                  <div className="flex items-start space-x-3">
                    <div className="text-amber-500 mt-1">
                      <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                        <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
                      </svg>
                    </div>
                    <p className="text-amber-800">
                      This document (&quot;Terms of Use&quot; or &quot;TOU&quot;) is an electronic record under applicable Information Technology laws. It has been generated by a computer system and does not require physical authentication.
                    </p>
                  </div>
                </div>

                <div className="bg-blue-50 p-6 rounded-lg border-l-4 border-blue-400">
                  <div className="flex items-start space-x-3">
                    <div className="text-blue-500 mt-1">
                      <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                        <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
                      </svg>
                    </div>
                    <div>
                      <strong className="text-blue-800">Important:</strong>
                      <p className="text-blue-700 mt-1">
                        By accessing www.infinityarthvishva.com or the Infinity Arthvishva Advisory Pvt. Ltd. mobile application (the &quot;Site&quot; or &quot;Website&quot;), you agree to the terms of this legal agreement between you (&quot;User&quot;) and Infinity Arthvishva Advisory Pvt. Ltd. (the &quot;Company&quot;).
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              {/* Table of Contents */}
              <div className="bg-gray-50 p-6 rounded-lg">
                <h3 className="text-xl font-semibold text-[#2076C7] mb-4 flex items-center">
                  <svg className="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm0 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm0 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clipRule="evenodd" />
                  </svg>
                  Table of Contents
                </h3>
                <ul className="grid grid-cols-1 md:grid-cols-2 gap-2">
                  {[
                    { id: 'company-info', label: 'Company Information' },
                    { id: 'definitions', label: 'Definitions' },
                    { id: 'services', label: 'Services' },
                    { id: 'terms', label: 'Detailed Terms' },
                    { id: 'acceptance', label: 'Acceptance' }
                  ].map((item) => (
                    <li key={item.id}>
                      <button
                        onClick={() => scrollToSection(item.id)}
                        className={`w-full text-left px-3 py-2 rounded-lg transition-all duration-200 ${
                          activeSection === item.id
                            ? 'bg-gradient-to-r from-[#2076C7] to-[#1CADA3] text-white shadow-md'
                            : 'text-gray-600 hover:bg-gray-100 hover:text-[#2076C7]'
                        }`}
                      >
                        {item.label}
                      </button>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Company Information */}
              <section id="company-info" className="space-y-4 scroll-mt-20">
                <h2 className="text-2xl font-semibold text-[#2076C7] border-l-4 border-[#1CADA3] pl-4 flex items-center">
                  <svg className="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M4 4a2 2 0 012-2h8a2 2 0 012 2v12a1 1 0 110 2h-3a1 1 0 01-1-1v-2a1 1 0 00-1-1H9a1 1 0 00-1 1v2a1 1 0 01-1 1H4a1 1 0 110-2V4zm3 1h2v2H7V5zm2 4H7v2h2V9zm2-4h2v2h-2V5zm2 4h-2v2h2V9z" clipRule="evenodd" />
                  </svg>
                  Company Information
                </h2>
                <p className="text-gray-700">The Company is incorporated under the Companies Act, 2013, with its registered office at:</p>
                <div className="bg-gray-50 p-6 rounded-lg border-l-4 border-[#2076C7] hover:bg-gray-100 transition-colors duration-200">
                  <div className="flex items-start space-x-3">
                    <div className="text-[#2076C7] mt-1">
                      <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                        <path fillRule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clipRule="evenodd" />
                      </svg>
                    </div>
                    <p className="text-gray-700">
                      7 Business Square by Naiknavare, Ganeshkhind Rd, Model Colony, Shivajinagar, Pune, Maharashtra 411016.
                    </p>
                  </div>
                </div>
              </section>

              {/* Definitions */}
              <section id="definitions" className="space-y-6 scroll-mt-20">
                <h2 className="text-2xl font-semibold text-[#2076C7] border-l-4 border-[#1CADA3] pl-4 flex items-center">
                  <svg className="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20">
                    <path d="M9 4.804A7.968 7.968 0 005.5 4c-1.255 0-2.443.29-3.5.804v10A7.969 7.969 0 015.5 14c1.669 0 3.218.51 4.5 1.385A7.962 7.962 0 0114.5 14c1.255 0 2.443.29 3.5.804v-10A7.968 7.968 0 0014.5 4c-1.255 0-2.443.29-3.5.804V12a1 1 0 11-2 0V4.804z" />
                  </svg>
                  Definitions
                </h2>
                
                <div className="space-y-4">
                  {[
                    {
                      term: '"User", "Client", or "You"',
                      definition: 'Refers to the individual using the Website/Mobile Application.'
                    },
                    {
                      term: '"Company"',
                      definition: 'Refers to Infinity Arthvishva Advisory Pvt. Ltd. and its affiliates/subsidiaries.'
                    },
                    {
                      term: '"Site" or "Website"',
                      definition: 'Refers to www.infinityarthvishva.com and associated sites, including content such as software, materials, text, images, videos, and applications.'
                    },
                    {
                      term: '"Product" or "Services"',
                      definition: 'Refers to financial and insurance products and services, including general insurance, life insurance, and related services provided by the Company.'
                    }
                  ].map((item, index) => (
                    <div 
                      key={index}
                      className="bg-gray-50 p-6 rounded-lg border-l-4 border-[#2076C7] hover:bg-gray-100 transition-colors duration-200"
                    >
                      <div className="font-semibold text-[#2076C7] mb-2">{item.term}</div>
                      <p className="text-gray-700">{item.definition}</p>
                    </div>
                  ))}
                </div>
              </section>

              {/* Services */}
              <section id="services" className="space-y-6 scroll-mt-20">
                <h2 className="text-2xl font-semibold text-[#2076C7] border-l-4 border-[#1CADA3] pl-4 flex items-center">
                  <svg className="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20">
                    <path d="M10 3.5a1.5 1.5 0 013 0V4a1 1 0 001 1h3a1 1 0 011 1v3a1 1 0 01-1 1h-.5a1.5 1.5 0 000 3h.5a1 1 0 011 1v3a1 1 0 01-1 1h-3a1 1 0 01-1-1v-.5a1.5 1.5 0 00-3 0v.5a1 1 0 01-1 1H6a1 1 0 01-1-1v-3a1 1 0 00-1-1h-.5a1.5 1.5 0 010-3H4a1 1 0 001-1V6a1 1 0 011-1h3a1 1 0 001-1v-.5z" />
                  </svg>
                  Services
                </h2>
                <p className="text-gray-700">
                  The Company distributes financial products like loans, mortgages, and insurance. By using the Website/Mobile Application, you agree to these terms.
                </p>
                
                <div className="space-y-4">
                  {[
                    {
                      icon: 'check-circle',
                      term: 'Access & Termination',
                      definition: 'The Company may suspend or terminate your access if you violate these terms, privacy policies, or applicable laws.'
                    },
                    {
                      icon: 'share-alt',
                      term: 'Information Sharing',
                      definition: 'The User consents to the sharing of their information with third parties at the Company\'s discretion and with group companies.'
                    },
                    {
                      icon: 'file-contract',
                      term: 'Electronic Communications',
                      definition: 'The User agrees that all agreements, notices, disclosures, and other communications provided electronically satisfy any legal requirement for written communications.'
                    }
                  ].map((item, index) => (
                    <div 
                      key={index}
                      className="bg-gray-50 p-6 rounded-lg border-l-4 border-[#2076C7] hover:bg-gray-100 transition-colors duration-200"
                    >
                      <div className="flex items-center space-x-3 mb-2">
                        <div className="text-[#1CADA3]">
                          <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                            <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                          </svg>
                        </div>
                        <div className="font-semibold text-[#2076C7]">{item.term}</div>
                      </div>
                      <p className="text-gray-700 ml-8">{item.definition}</p>
                    </div>
                  ))}
                </div>
              </section>

              {/* Detailed Terms */}
              <section id="terms" className="space-y-6 scroll-mt-20">
                <h2 className="text-2xl font-semibold text-[#2076C7] border-l-4 border-[#1CADA3] pl-4 flex items-center">
                  <svg className="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M4 4a2 2 0 012-2h4.586A2 2 0 0112 2.586L15.414 6A2 2 0 0116 7.414V16a2 2 0 01-2 2H6a2 2 0 01-2-2V4zm2 6a1 1 0 011-1h6a1 1 0 110 2H7a1 1 0 01-1-1zm1 3a1 1 0 100 2h6a1 1 0 100-2H7z" clipRule="evenodd" />
                  </svg>
                  Detailed Terms
                </h2>
                
                <div className="space-y-6">
                  <div>
                    <h3 className="text-xl font-semibold text-[#1CADA3] mb-3">Feedback</h3>
                    <p className="text-gray-700 leading-relaxed">
                      Unless explicitly stated otherwise, all comments, feedback, information, or materials submitted to the Company via this Website/Mobile Application will be considered the Company&apos;s property. By submitting such content, the User assigns all worldwide rights, including intellectual property rights, to the Company.
                    </p>
                  </div>
                  
                  <div>
                    <h3 className="text-xl font-semibold text-[#1CADA3] mb-3">Ownership</h3>
                    <p className="text-gray-700 leading-relaxed">
                      The Website/Mobile Application contains various information and materials protected by intellectual property rights owned by the Company, its affiliates, subsidiaries, or third parties. All trademarks and copyrighted content are the property of their respective owners.
                    </p>
                  </div>
                  
                  <div>
                    <h3 className="text-xl font-semibold text-[#1CADA3] mb-3">User Responsibilities</h3>
                    <p className="text-gray-700 leading-relaxed">
                      The User is solely responsible for maintaining the confidentiality of their password and Login ID. The User agrees to provide true, accurate, and complete information and promptly update it as needed.
                    </p>
                  </div>
                  
                  <div>
                    <h3 className="text-xl font-semibold text-[#1CADA3] mb-3">Eligibility and Use</h3>
                    <p className="text-gray-700 leading-relaxed">
                      By using the Website/Mobile Application, the User confirms they are of legal age to form a binding contract and not barred from receiving services under applicable laws. Users may only maintain one active account.
                    </p>
                  </div>
                  
                  <div>
                    <h3 className="text-xl font-semibold text-[#1CADA3] mb-3">Third-Party Links/Offers</h3>
                    <p className="text-gray-700 leading-relaxed">
                      The Website may include links to third-party websites. The Company is not responsible for their availability or content and does not endorse materials provided by these external resources.
                    </p>
                  </div>
                </div>
              </section>

              {/* Acceptance */}
              <section id="acceptance" className="scroll-mt-20">
                <div className="bg-green-50 p-6 rounded-lg border-l-4 border-green-400">
                  <div className="flex items-start space-x-3">
                    <div className="text-green-500 mt-1">
                      <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                        <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                      </svg>
                    </div>
                    <p className="text-green-800">
                      By using this Website/Mobile Application, you acknowledge that you have read, understood, and agree to be bound by these Terms of Use.
                    </p>
                  </div>
                </div>
              </section>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}